"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29 08:10:38.655875
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_path', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_models')),
    sa.UniqueConstraint('name', 'version', name='uq_ai_models_name_version')
    )
    op.create_index(op.f('ix_ai_models_name'), 'ai_models', ['name'], unique=False)
    op.create_table('sites',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('name', name=op.f('uq_sites_name'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('edge_devices',
    sa.Column('device_uuid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'online', 'offline', name='device_status'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('gpu_name', sa.String(length=128), nullable=True),
    sa.Column('gpu_memory', sa.Integer(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('gpu_usage', sa.Float(), nullable=True),
    sa.Column('gpu_memory_usage', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_edge_devices_site_id_sites'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edge_devices')),
    sa.UniqueConstraint('api_key_hash', name=op.f('uq_edge_devices_api_key_hash'))
    )
    op.create_index(op.f('ix_edge_devices_device_uuid'), 'edge_devices', ['device_uuid'], unique=True)
    op.create_index(op.f('ix_edge_devices_site_id'), 'edge_devices', ['site_id'], unique=False)
    op.create_index(op.f('ix_edge_devices_status'), 'edge_devices', ['status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('cameras',
    sa.Column('edge_device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rtsp_url', sa.String(length=512), nullable=False),
    sa.Column('rtsp_username', sa.String(length=128), nullable=True),
    sa.Column('rtsp_password_encrypted', sa.Text(), nullable=True),
    sa.Column('onvif_url', sa.String(length=512), nullable=True),
    sa.Column('stream_id', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_model_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('unknown', 'online', 'offline', 'error', name='camera_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], name=op.f('fk_cameras_ai_model_id_ai_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edge_device_id'], ['edge_devices.id'], name=op.f('fk_cameras_edge_device_id_edge_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_index(op.f('ix_cameras_edge_device_id'), 'cameras', ['edge_device_id'], unique=False)
    op.create_index(op.f('ix_cameras_stream_id'), 'cameras', ['stream_id'], unique=True)
    op.create_table('detection_events',
    sa.Column('event_group_id', sa.Uuid(), nullable=False),
    sa.Column('detection_index', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('edge_device_id', sa.Uuid(), nullable=False),
    sa.Column('ai_model_id', sa.Uuid(), nullable=True),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_url', sa.String(length=512), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], name=op.f('fk_detection_events_ai_model_id_ai_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_detection_events_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edge_device_id'], ['edge_devices.id'], name=op.f('fk_detection_events_edge_device_id_edge_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_events')),
    sa.UniqueConstraint('event_group_id', 'detection_index', name='uq_detection_events_group_index')
    )
    op.create_index('ix_detection_events_camera_time', 'detection_events', ['camera_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_detection_events_class_name'), 'detection_events', ['class_name'], unique=False)
    op.create_index('ix_detection_events_detected_at', 'detection_events', ['detected_at'], unique=False)
    op.create_index('ix_detection_events_device_time', 'detection_events', ['edge_device_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_detection_events_event_group_id'), 'detection_events', ['event_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_events_event_group_id'), table_name='detection_events')
    op.drop_index('ix_detection_events_device_time', table_name='detection_events')
    op.drop_index('ix_detection_events_detected_at', table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_class_name'), table_name='detection_events')
    op.drop_index('ix_detection_events_camera_time', table_name='detection_events')
    op.drop_table('detection_events')
    op.drop_index(op.f('ix_cameras_stream_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_edge_device_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_edge_devices_status'), table_name='edge_devices')
    op.drop_index(op.f('ix_edge_devices_site_id'), table_name='edge_devices')
    op.drop_index(op.f('ix_edge_devices_device_uuid'), table_name='edge_devices')
    op.drop_table('edge_devices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('sites')
    op.drop_index(op.f('ix_ai_models_name'), table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
    bind = op.get_bind()
    for enum_name in ("camera_status", "device_status", "user_role"):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
